spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Manasa@1998
    url: jdbc:mysql://localhost:3306/Employee
    username: root
  boot:
    admin:
      client:
        url: http://localhost:1111/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
springdoc:
  swagger-ui:
     path: swagger-ui.html  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: health    
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0      
